### ISSUE TITLE
Easy Installer

### ISSUE THREAD

**Issue by ArxdSilva** [XML-Comp/XML-Comp#12]
This installer needs to provide people without programming skills a way of installing It without having to install Go first.

We might need some kind of `requirements.txt`  file or `vendor` folder to help It or some kind of [`MAKEFILE`](https://github.com/globocom/megadraft/blob/master/Makefile)

**Comment by ArxdSilva** [comment]
More ideas on Issue #2

**Comment by dixonwille** [comment]
@ArxdSilva So you should not need an installer? If you are building a CLI then you can cross compile your code and tag the release and include the binaries there. If you would like to include it in the path so user doesn't have to remember where it is then research into an installer that can edit environment variables is a must.

**Comment by dixonwille** [comment]
Just read the other issue. I think the installer will depend on your GUI option you want in Issue #10
